// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/extensions/IERC20Permit.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";
import "./interfaces/ISubscriptionManager.sol";

/// @title SubscriptionManager
/// @notice On-chain subscription billing contract for SweepConsole.
///         Hybrid Settlement-Window Escrow + Allowance Recurring, push settlement,
///         non-custodial merchant payout wallets on Arc.
///
/// @dev Architecture (per the Subscription Protocol implementation addendum):
///      - FIRST payments and trial conversions are held in per-subscription escrow
///        until settlementDeadline passes; the settlement window is the ONLY refund
///        path. After the window closes, settlePeriod() PUSHES the merchant share
///        directly to merchantPayout and the fee to platformTreasury in one tx.
///      - All renewals are allowance-based: renewFromAllowance() pulls from the
///        subscriber's pre-approved USDC allowance and pushes the split immediately.
///        Merchants never sign a claim transaction — there is no claimFunds().
///      - The platform (owner) is the arbiter: it signs settlePeriod(),
///        renewFromAllowance(), and refund() calls from the off-chain billing engine.
///      - refund() operates ONLY on escrowBalance. Funds already pushed to a
///        merchant cannot be recovered by this contract.
///
/// @custom:security-note
///      First checkout produces exactly two subscriber signatures:
///        1. USDC.approve(subscriptionManagerAddress, amount * 12)  // one year
///        2. subscribe(...)                                          // first period into escrow
///      Renewals produce zero subscriber signatures. Revoking the allowance from
///      the wallet effectively cancels future renewals.
contract SubscriptionManager is ISubscriptionManager, Ownable, ReentrancyGuard, Pausable {
    using SafeERC20 for IERC20;

    // ─── Immutables ───────────────────────────────────────────────────────────

    /// @notice USDC token contract on Arc
    IERC20 public immutable usdc;

    // ─── Constants ────────────────────────────────────────────────────────────

    /// @notice Billing engine retries daily up to 7 times before cancelling
    uint8 public constant MAX_RETRIES = 7;

    // ─── State ────────────────────────────────────────────────────────────────

    /// @notice Wallet that receives the platform's share of every payment
    address public platformTreasury;

    /// @notice Platform fee in basis points (100 = 1%, max 1000 = 10%)
    uint256 public platformFeeBps;

    /// @notice subscriptionId (platform-generated bytes32) => Subscription
    mapping(bytes32 => Subscription) private _subscriptions;

    // ─── Constructor ──────────────────────────────────────────────────────────

    constructor(
        address _usdc,
        address _platformTreasury,
        uint256 _platformFeeBps
    ) Ownable(msg.sender) {
        if (_usdc == address(0)) revert InvalidAddress();
        if (_platformTreasury == address(0)) revert InvalidAddress();
        if (_platformFeeBps > 1000) revert FeeTooHigh(_platformFeeBps);

        usdc = IERC20(_usdc);
        platformTreasury = _platformTreasury;
        platformFeeBps = _platformFeeBps;
    }

    // ─── Subscriber-Callable ──────────────────────────────────────────────────

    /// @notice Activate a new subscription.
    ///
    ///         Before calling, the subscriber must have called:
    ///           USDC.approve(address(this), amount * 12)   // one year allowance
    ///
    ///         If trialDuration == 0, the first period is pulled into escrow and
    ///         held until `settlementWindow` seconds pass (the refund window).
    ///         If trialDuration > 0, no payment is taken until the trial ends; the
    ///         billing engine then calls renewFromAllowance(), and that trial
    ///         conversion is escrowed for the same window.
    ///
    /// @param subId             Unique bytes32 ID generated by the platform off-chain
    /// @param merchantPayout    Verified merchant payout address (Circle user-controlled or external)
    /// @param planId            bytes32 plan identifier (off-chain plan reference)
    /// @param amount            USDC amount per cycle (6 decimals: 9_000_000 = $9.00)
    /// @param interval          Billing cycle length in seconds (2_592_000 = 30 days)
    /// @param trialDuration     Trial length in seconds. Pass 0 for no trial.
    /// @param settlementWindow  Escrow hold in seconds (per-plan; default 24h for first payments)
    function subscribe(
        bytes32 subId,
        address merchantPayout,
        bytes32 planId,
        uint256 amount,
        uint256 interval,
        uint256 trialDuration,
        uint256 settlementWindow
    ) external nonReentrant whenNotPaused {
        _createSubscription(
            msg.sender, subId, merchantPayout, planId, amount, interval, trialDuration, settlementWindow
        );
    }

    /// @notice Gasless activation. Platform-only: the subscriber signs ONLY an
    ///         EIP-2612 permit off-chain (one signature, no gas); the platform
    ///         submits this tx and pays Arc gas. The permit grants the recurring
    ///         allowance, then the first period is pulled into settlement-window
    ///         escrow from the subscriber's Arc USDC. Cross-chain checkouts mint to
    ///         the subscriber via CCTP off-chain, then activate through this path.
    function subscribeWithPermit(SubscriptionActivation calldata activation)
        external
        nonReentrant
        whenNotPaused
        onlyOwner
    {
        _applyPermit(activation);
        _createFromActivation(activation);
    }

    /// @notice Cancel a subscription. Callable by the subscriber themselves or the platform.
    ///         Any USDC still held in escrow is returned to the subscriber in the same tx.
    ///         The frontend should prompt the subscriber to revoke the USDC allowance.
    function cancelSubscription(bytes32 subId) external nonReentrant {
        Subscription storage sub = _subscriptions[subId];

        if (sub.subscriber == address(0)) revert SubscriptionNotFound(subId);
        if (sub.status == Status.Cancelled) revert SubscriptionNotActive(subId);
        if (msg.sender != sub.subscriber && msg.sender != owner()) {
            revert UnauthorizedCaller(msg.sender);
        }

        uint256 refundedEscrow = sub.escrowBalance;
        sub.escrowBalance = 0;
        sub.settlementDeadline = 0;
        sub.status = Status.Cancelled;

        if (refundedEscrow > 0) {
            usdc.safeTransfer(sub.subscriber, refundedEscrow);
        }

        emit SubscriptionCancelled(subId, refundedEscrow);
    }

    // ─── Platform-Only (Billing Engine / Arbiter) ─────────────────────────────

    /// @notice Release escrowed funds once the settlement window has closed.
    ///         PUSHES the merchant share directly to merchantPayout and the
    ///         platform fee to platformTreasury in a single transaction — the
    ///         merchant never signs a claim.
    function settlePeriod(bytes32 subId) external nonReentrant whenNotPaused onlyOwner {
        Subscription storage sub = _subscriptions[subId];

        if (sub.subscriber == address(0)) revert SubscriptionNotFound(subId);
        if (sub.escrowBalance == 0) revert NothingInEscrow(subId);
        if (block.timestamp < sub.settlementDeadline) {
            revert SettlementNotDue(subId, sub.settlementDeadline, block.timestamp);
        }

        uint256 escrow = sub.escrowBalance;
        sub.escrowBalance = 0;
        sub.settlementDeadline = 0;

        (uint256 merchantShare, uint256 fee) = _split(escrow);
        _push(sub.merchantPayout, merchantShare, fee);

        emit PeriodSettled(subId, merchantShare, fee);
    }

    /// @notice Process a recurring renewal (or trial conversion) from the
    ///         subscriber's pre-approved USDC allowance. Arbiter-only.
    ///
    ///         Trial conversions are the subscription's FIRST payment, so they are
    ///         pulled into escrow and held for the settlement window. Standard
    ///         renewals are split and PUSHED to merchantPayout immediately.
    ///
    ///         Emits PaymentFailed (and returns false without reverting) when the
    ///         subscriber has insufficient allowance or balance — the billing
    ///         engine then enters the retry cycle (daily × 7) before cancelling.
    function renewFromAllowance(bytes32 subId)
        external
        nonReentrant
        whenNotPaused
        onlyOwner
        returns (bool)
    {
        Subscription storage sub = _subscriptions[subId];

        if (sub.subscriber == address(0)) revert SubscriptionNotFound(subId);
        if (sub.status == Status.Cancelled || sub.status == Status.None) {
            revert SubscriptionNotActive(subId);
        }
        if (block.timestamp < sub.nextBillingDate) {
            revert BillingTooEarly(subId, sub.nextBillingDate, block.timestamp);
        }

        // Check funds without reverting so the engine can run its retry cycle
        uint256 allowance = usdc.allowance(sub.subscriber, address(this));
        if (allowance < sub.amount) {
            _recordFailure(sub, subId, "Insufficient USDC allowance");
            return false;
        }
        uint256 balance = usdc.balanceOf(sub.subscriber);
        if (balance < sub.amount) {
            _recordFailure(sub, subId, "Insufficient USDC balance");
            return false;
        }

        bool isTrialConversion = sub.status == Status.Trialing;

        usdc.safeTransferFrom(sub.subscriber, address(this), sub.amount);

        if (isTrialConversion) {
            // First real payment — hold in escrow for the settlement window
            sub.escrowBalance += sub.amount;
            sub.settlementDeadline = block.timestamp + sub.settlementWindow;
        } else {
            (uint256 merchantShare, uint256 fee) = _split(sub.amount);
            _push(sub.merchantPayout, merchantShare, fee);
        }

        sub.status = Status.Active;
        sub.retryCount = 0;
        sub.nextBillingDate = block.timestamp + sub.interval;

        emit SubscriptionRenewed(subId, sub.amount, sub.nextBillingDate);
        return true;
    }

    /// @notice Issue a pro-rated refund to the subscriber. Arbiter-only.
    ///         Operates ONLY on escrowBalance — funds already pushed to the
    ///         merchant cannot be recovered without merchant cooperation.
    /// @param refundPct  Percentage of the escrowed amount to refund (1–100)
    function refund(bytes32 subId, uint8 refundPct) external nonReentrant onlyOwner {
        Subscription storage sub = _subscriptions[subId];

        if (sub.subscriber == address(0)) revert SubscriptionNotFound(subId);
        if (refundPct == 0 || refundPct > 100) revert InvalidPercentage(refundPct);
        if (sub.escrowBalance == 0) revert NothingInEscrow(subId);

        uint256 refundAmount = (sub.escrowBalance * refundPct) / 100;
        sub.escrowBalance -= refundAmount;
        if (sub.escrowBalance == 0) sub.settlementDeadline = 0;

        usdc.safeTransfer(sub.subscriber, refundAmount);

        emit Refunded(subId, refundAmount, refundPct);
    }

    // ─── Admin ────────────────────────────────────────────────────────────────

    function updatePlatformFee(uint256 newFeeBps) external onlyOwner {
        if (newFeeBps > 1000) revert FeeTooHigh(newFeeBps);
        emit PlatformFeeUpdated(platformFeeBps, newFeeBps);
        platformFeeBps = newFeeBps;
    }

    function updatePlatformTreasury(address newTreasury) external onlyOwner {
        if (newTreasury == address(0)) revert InvalidAddress();
        emit PlatformTreasuryUpdated(platformTreasury, newTreasury);
        platformTreasury = newTreasury;
    }

    function pause() external onlyOwner { _pause(); }
    function unpause() external onlyOwner { _unpause(); }

    // ─── Views ────────────────────────────────────────────────────────────────

    function getSubscription(bytes32 subId) external view returns (Subscription memory) {
        return _subscriptions[subId];
    }

    function isSubscriptionActive(bytes32 subId) external view returns (bool) {
        Status s = _subscriptions[subId].status;
        return s == Status.Trialing || s == Status.Active || s == Status.PastDue;
    }

    /// @notice Returns true when a subscription is billable and past its nextBillingDate.
    ///         Used by the billing engine to build its renewal batch.
    function isDueBilling(bytes32 subId) external view returns (bool) {
        Subscription memory sub = _subscriptions[subId];
        return
            (sub.status == Status.Trialing || sub.status == Status.Active || sub.status == Status.PastDue) &&
            block.timestamp >= sub.nextBillingDate;
    }

    /// @notice Returns true when escrowed funds are past their settlement deadline.
    ///         Used by the billing engine to build its settlement batch.
    function isDueSettlement(bytes32 subId) external view returns (bool) {
        Subscription memory sub = _subscriptions[subId];
        return sub.escrowBalance > 0 && block.timestamp >= sub.settlementDeadline;
    }

    // ─── Internal ─────────────────────────────────────────────────────────────

    /// @dev Applies the subscriber's EIP-2612 permit to grant this contract the
    ///      recurring allowance. Tolerates failure (front-run / already used) —
    ///      _createSubscription still enforces the allowance via _pullIntoEscrow.
    function _applyPermit(SubscriptionActivation calldata activation) internal {
        if (activation.permitValue > 0) {
            try IERC20Permit(address(usdc)).permit(
                activation.subscriber,
                address(this),
                activation.permitValue,
                activation.permitDeadline,
                activation.permitV,
                activation.permitR,
                activation.permitS
            ) {} catch {}
        }
    }

    /// @dev Creates a subscription from a platform-submitted activation payload.
    function _createFromActivation(SubscriptionActivation calldata activation) internal {
        _createSubscription(
            activation.subscriber,
            activation.subId,
            activation.merchantPayout,
            activation.planId,
            activation.amount,
            activation.interval,
            activation.trialDuration,
            activation.settlementWindow
        );
    }

    /// @dev Shared activation logic for subscribe() (subscriber-signed) and
    ///      subscribeWithPermit() (platform-signed). Without a trial the first
    ///      period is pulled into settlement-window escrow; with a trial nothing
    ///      is charged until the trial converts.
    function _createSubscription(
        address subscriber,
        bytes32 subId,
        address merchantPayout,
        bytes32 planId,
        uint256 amount,
        uint256 interval,
        uint256 trialDuration,
        uint256 settlementWindow
    ) internal {
        if (_subscriptions[subId].subscriber != address(0)) {
            revert SubscriptionAlreadyExists(subId);
        }
        if (amount == 0) revert InvalidAmount();
        if (interval == 0) revert InvalidInterval();
        if (merchantPayout == address(0)) revert InvalidAddress();

        bool hasTrial = trialDuration > 0;

        if (hasTrial) {
            uint256 trialEnd = block.timestamp + trialDuration;

            _subscriptions[subId] = Subscription({
                subscriber: subscriber,
                merchantPayout: merchantPayout,
                planId: planId,
                amount: amount,
                interval: interval,
                nextBillingDate: trialEnd,
                trialEnd: trialEnd,
                escrowBalance: 0,
                settlementDeadline: 0,
                settlementWindow: settlementWindow,
                retryCount: 0,
                status: Status.Trialing
            });
        } else {
            _pullIntoEscrow(subscriber, amount);

            _subscriptions[subId] = Subscription({
                subscriber: subscriber,
                merchantPayout: merchantPayout,
                planId: planId,
                amount: amount,
                interval: interval,
                nextBillingDate: block.timestamp + interval,
                trialEnd: 0,
                escrowBalance: amount,
                settlementDeadline: block.timestamp + settlementWindow,
                settlementWindow: settlementWindow,
                retryCount: 0,
                status: Status.Active
            });
        }

        emit SubscriptionCreated(subId, subscriber, merchantPayout, planId);
    }

    /// @dev Pulls the first payment into the contract's escrow. Reverts on failure
    ///      since the subscriber is signing this transaction interactively.
    function _pullIntoEscrow(address subscriber, uint256 amount) internal {
        uint256 allowance = usdc.allowance(subscriber, address(this));
        if (allowance < amount) revert InsufficientAllowance(subscriber, amount, allowance);

        uint256 balance = usdc.balanceOf(subscriber);
        if (balance < amount) revert InsufficientBalance(subscriber, amount, balance);

        usdc.safeTransferFrom(subscriber, address(this), amount);
    }

    function _split(uint256 amount) internal view returns (uint256 merchantShare, uint256 fee) {
        fee = (amount * platformFeeBps) / 10_000;
        merchantShare = amount - fee;
    }

    /// @dev Pushes the merchant share and platform fee out in the same transaction.
    function _push(address merchantPayout, uint256 merchantShare, uint256 fee) internal {
        usdc.safeTransfer(merchantPayout, merchantShare);
        if (fee > 0) {
            usdc.safeTransfer(platformTreasury, fee);
        }
    }

    function _recordFailure(Subscription storage sub, bytes32 subId, string memory reason) internal {
        sub.status = Status.PastDue;
        if (sub.retryCount < MAX_RETRIES) {
            sub.retryCount += 1;
        }
        emit PaymentFailed(subId, sub.retryCount, reason);
    }
}
