// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";
import "./interfaces/ISubscriptionManager.sol";

/// @title SubscriptionManager
/// @notice On-chain subscription billing contract for SweepConsole.
///         Handles USDC collection, escrow, recurring renewals, and merchant payouts on Arc.
///
/// @dev Architecture:
///      - The platform (owner) is the only address allowed to call renew() and refund(),
///        since those are triggered by the off-chain billing engine.
///      - Subscribers call subscribe() directly after approving a USDC allowance.
///      - USDC flows: subscriber wallet → this contract → merchantBalances[merchant]
///        Platform fee is deducted at collection time and credited to platformTreasury.
///      - Merchants pull their USDC by calling claimFunds(); the contract never pushes.
///
/// @custom:security-note
///      Subscribers must call USDC.approve(subscriptionManagerAddress, amount * cycles)
///      before calling subscribe(). The recommended allowance is amount * 12 (one year).
///      Revoking this allowance at any time from the wallet effectively cancels future renewals.
contract SubscriptionManager is ISubscriptionManager, Ownable, ReentrancyGuard, Pausable {
    using SafeERC20 for IERC20;

    // ─── Immutables ───────────────────────────────────────────────────────────

    /// @notice USDC token contract on Arc
    IERC20 public immutable usdc;

    // ─── State ────────────────────────────────────────────────────────────────

    /// @notice Wallet that receives the platform's share of every payment
    address public platformTreasury;

    /// @notice Platform fee in basis points (100 = 1%, max 1000 = 10%)
    uint256 public platformFeeBps;

    /// @notice subscriptionId (platform-generated bytes32) => Subscription
    mapping(bytes32 => Subscription) private _subscriptions;

    /// @notice Accumulated USDC owed to each merchant (and to platformTreasury)
    mapping(address => uint256) private _balances;

    // ─── Constructor ──────────────────────────────────────────────────────────

    constructor(
        address _usdc,
        address _platformTreasury,
        uint256 _platformFeeBps
    ) Ownable(msg.sender) {
        if (_usdc == address(0)) revert InvalidAddress();
        if (_platformTreasury == address(0)) revert InvalidAddress();
        if (_platformFeeBps > 1000) revert FeeTooHigh(_platformFeeBps);

        usdc = IERC20(_usdc);
        platformTreasury = _platformTreasury;
        platformFeeBps = _platformFeeBps;
    }

    // ─── Subscriber-Callable ──────────────────────────────────────────────────

    /// @notice Activate a new subscription.
    ///
    ///         Before calling, the subscriber must have called:
    ///           USDC.approve(address(this), amount * 12)   // one year allowance
    ///
    ///         If trialDuration == 0, the first payment is collected immediately.
    ///         If trialDuration > 0, no payment is taken until the trial ends; the
    ///         billing engine calls renew() after the trial expires.
    ///
    /// @param subscriptionId  Unique bytes32 ID generated by the platform off-chain
    /// @param merchant        Merchant wallet that receives payments
    /// @param amount          USDC amount per cycle (6 decimals: 9_000_000 = $9.00)
    /// @param interval        Billing cycle length in seconds (2_592_000 = 30 days)
    /// @param trialDuration   Trial length in seconds. Pass 0 for no trial.
    function subscribe(
        bytes32 subscriptionId,
        address merchant,
        uint256 amount,
        uint256 interval,
        uint256 trialDuration
    ) external nonReentrant whenNotPaused {
        if (_subscriptions[subscriptionId].subscriber != address(0)) {
            revert SubscriptionAlreadyExists(subscriptionId);
        }
        if (amount == 0) revert InvalidAmount();
        if (interval == 0) revert InvalidInterval();
        if (merchant == address(0)) revert InvalidAddress();

        bool hasTrial = trialDuration > 0;

        if (hasTrial) {
            uint256 trialEndAt = block.timestamp + trialDuration;

            _subscriptions[subscriptionId] = Subscription({
                subscriber: msg.sender,
                merchant: merchant,
                amount: amount,
                interval: interval,
                nextBillingAt: trialEndAt,
                active: true,
                trialing: true,
                trialEndAt: trialEndAt
            });

            emit SubscriptionCreated(subscriptionId, msg.sender, merchant, amount, interval, true);
            emit TrialStarted(subscriptionId, msg.sender, trialEndAt);
        } else {
            _collectPayment(subscriptionId, msg.sender, merchant, amount);

            _subscriptions[subscriptionId] = Subscription({
                subscriber: msg.sender,
                merchant: merchant,
                amount: amount,
                interval: interval,
                nextBillingAt: block.timestamp + interval,
                active: true,
                trialing: false,
                trialEndAt: 0
            });

            emit SubscriptionCreated(subscriptionId, msg.sender, merchant, amount, interval, false);
        }
    }

    /// @notice Cancel a subscription. Callable by the subscriber themselves or the platform.
    ///         Does NOT issue a refund — use refund() separately if needed.
    function cancel(bytes32 subscriptionId) external nonReentrant {
        Subscription storage sub = _subscriptions[subscriptionId];

        if (sub.subscriber == address(0)) revert SubscriptionNotFound(subscriptionId);
        if (!sub.active) revert SubscriptionNotActive(subscriptionId);
        if (msg.sender != sub.subscriber && msg.sender != owner()) {
            revert UnauthorizedCaller(msg.sender);
        }

        sub.active = false;
        emit SubscriptionCancelled(subscriptionId, sub.subscriber, sub.merchant);
    }

    /// @notice Merchant pulls their accumulated USDC out of the contract.
    function claimFunds() external nonReentrant {
        uint256 balance = _balances[msg.sender];
        if (balance == 0) return;

        _balances[msg.sender] = 0;
        usdc.safeTransfer(msg.sender, balance);

        emit FundsClaimed(msg.sender, balance);
    }

    // ─── Platform-Only (Billing Engine) ───────────────────────────────────────

    /// @notice Process a recurring renewal for one subscription.
    ///         Only callable by the platform owner (billing engine wallet).
    ///         Emits PaymentFailed (and returns without reverting) if the subscriber
    ///         has insufficient allowance or balance — the billing engine then enters
    ///         the retry cycle and eventually cancels after max retries.
    function renew(bytes32 subscriptionId) external nonReentrant whenNotPaused onlyOwner {
        Subscription storage sub = _subscriptions[subscriptionId];

        if (sub.subscriber == address(0)) revert SubscriptionNotFound(subscriptionId);
        if (!sub.active) revert SubscriptionNotActive(subscriptionId);
        if (sub.trialing && block.timestamp < sub.trialEndAt) {
            revert StillTrialing(subscriptionId, sub.trialEndAt);
        }
        if (block.timestamp < sub.nextBillingAt) {
            revert BillingTooEarly(subscriptionId, sub.nextBillingAt, block.timestamp);
        }

        if (sub.trialing) {
            sub.trialing = false;
            emit TrialConverted(subscriptionId, sub.subscriber);
        }

        bool success = _tryCollectPayment(subscriptionId, sub.subscriber, sub.merchant, sub.amount);
        if (success) {
            sub.nextBillingAt = block.timestamp + sub.interval;
            emit SubscriptionRenewed(subscriptionId, sub.subscriber, sub.merchant, sub.amount);
        }
    }

    /// @notice Issue a pro-rated USDC refund to a subscriber.
    ///         Deducted from the merchant's claimable balance.
    ///         Only callable by the platform owner.
    function refund(bytes32 subscriptionId, uint256 amount) external nonReentrant onlyOwner {
        Subscription storage sub = _subscriptions[subscriptionId];

        if (sub.subscriber == address(0)) revert SubscriptionNotFound(subscriptionId);

        uint256 merchantBalance = _balances[sub.merchant];
        if (merchantBalance < amount) {
            revert InsufficientMerchantBalance(sub.merchant, amount, merchantBalance);
        }

        _balances[sub.merchant] -= amount;
        usdc.safeTransfer(sub.subscriber, amount);

        emit Refunded(subscriptionId, sub.subscriber, amount);
    }

    // ─── Admin ────────────────────────────────────────────────────────────────

    function updatePlatformFee(uint256 newFeeBps) external onlyOwner {
        if (newFeeBps > 1000) revert FeeTooHigh(newFeeBps);
        emit PlatformFeeUpdated(platformFeeBps, newFeeBps);
        platformFeeBps = newFeeBps;
    }

    function updatePlatformTreasury(address newTreasury) external onlyOwner {
        if (newTreasury == address(0)) revert InvalidAddress();
        emit PlatformTreasuryUpdated(platformTreasury, newTreasury);
        platformTreasury = newTreasury;
    }

    function pause() external onlyOwner { _pause(); }
    function unpause() external onlyOwner { _unpause(); }

    // ─── Views ────────────────────────────────────────────────────────────────

    function getSubscription(bytes32 subscriptionId) external view returns (Subscription memory) {
        return _subscriptions[subscriptionId];
    }

    function getMerchantBalance(address merchant) external view returns (uint256) {
        return _balances[merchant];
    }

    function isSubscriptionActive(bytes32 subscriptionId) external view returns (bool) {
        return _subscriptions[subscriptionId].active;
    }

    /// @notice Returns true when a subscription is active, past its trial, and past its nextBillingAt.
    ///         Used by the billing engine to build its renewal batch.
    function isDueBilling(bytes32 subscriptionId) external view returns (bool) {
        Subscription memory sub = _subscriptions[subscriptionId];
        return sub.active && !sub.trialing && block.timestamp >= sub.nextBillingAt;
    }

    // ─── Internal ─────────────────────────────────────────────────────────────

    /// @dev Collects payment, reverts on any failure. Used for initial subscribe().
    function _collectPayment(
        bytes32 subscriptionId,
        address subscriber,
        address merchant,
        uint256 amount
    ) internal {
        uint256 allowance = usdc.allowance(subscriber, address(this));
        if (allowance < amount) revert InsufficientAllowance(subscriber, amount, allowance);

        uint256 balance = usdc.balanceOf(subscriber);
        if (balance < amount) revert InsufficientBalance(subscriber, amount, balance);

        _splitAndCredit(subscriber, merchant, amount);
    }

    /// @dev Attempts payment collection, returns false and emits PaymentFailed instead of reverting.
    ///      Used for renew() so the billing engine can gracefully handle failures.
    function _tryCollectPayment(
        bytes32 subscriptionId,
        address subscriber,
        address merchant,
        uint256 amount
    ) internal returns (bool) {
        if (usdc.allowance(subscriber, address(this)) < amount) {
            emit PaymentFailed(subscriptionId, subscriber, "Insufficient USDC allowance");
            return false;
        }
        if (usdc.balanceOf(subscriber) < amount) {
            emit PaymentFailed(subscriptionId, subscriber, "Insufficient USDC balance");
            return false;
        }

        _splitAndCredit(subscriber, merchant, amount);
        return true;
    }

    /// @dev Pulls USDC from subscriber and credits merchant + treasury shares.
    function _splitAndCredit(address subscriber, address merchant, uint256 amount) internal {
        usdc.safeTransferFrom(subscriber, address(this), amount);

        uint256 fee = (amount * platformFeeBps) / 10_000;
        uint256 merchantShare = amount - fee;

        _balances[merchant] += merchantShare;
        if (fee > 0) {
            _balances[platformTreasury] += fee;
        }
    }
}
